### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by polka125** [eric-wieser/lean-matrix-cookbook#15]
Hi! I learned about your wanderfull project from a post [on twitter](https://x.com/thomasahle/status/1831794983768346920)

I am curious about several things: 

- are you open for outside contributors? 
- what is the process should look like?  For example to avoid the situation when several people work on the same theorem/lemma, should one take a ticket or announce their plan to work on some part? 
- what kind of contributions are possible and will benefit to the projext? (Like it is obvious that there are certain amount of `sorry` placeholders and todos in the text, but maybe some work remain in retyping statements from the textbook to lean.) 

Thanks!

**Comment by eric-wieser** [comment]
Hi @polka125! I can think of a couple ways to contribute here:

* **proofs:** ideally the contributions would be of the form "eq X.Y is (mostly) in Mathlib, it's provable in a few lines". If your result takes tens of lines to prove, then it should probably be a contribution to Mathlib instead. I am happy to help review such contributions on the Mathlib side!
* **statements:** I am happy to take contributions, but I fear that much of the low-hanging fruit has already gone. If you find some I've missed, a PR would definitely be welcome
* **infrastructure:** In the longer run it would be great to hook this up with leanprover-community/verso, using the OCR-extracted LaTeX that I have floating around on my hard-drive. I don't think verso is quite at the point where this makes sense to pursue just yet, but we're close.

> For example to avoid the situation when several people work on the same theorem/lemma, should one take a ticket or announce their plan to work on some part?

Opening a "draft" PR (and searching for existing ones) is a reasonable workflow here.

**Comment by polka125** [comment]
Hi @eric-wieser thanks for the extremely quick reply! I got answers to all my questions and therefore close the issue

**Comment by arademaker** [comment]
Just to lean the workflow ..  what would be a draft PR?

**Comment by eric-wieser** [comment]
Draft PRs are described at https://github.blog/news-insights/product-news/introducing-draft-pull-requests/
